// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgEn3CmxmRmbIa2uEPL2l732hrWiPb_1c',
    appId: '1:56301313056:web:3eb45e78387823b15e7045',
    messagingSenderId: '56301313056',
    projectId: 'harsh-potfolio',
    authDomain: 'harsh-potfolio.firebaseapp.com',
    storageBucket: 'harsh-potfolio.appspot.com',
    measurementId: 'G-4W0SC65SCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtsa4d-86RERuxwi_jDVnTwb7jOTWwD1o',
    appId: '1:56301313056:android:8f320cbe6ccc67095e7045',
    messagingSenderId: '56301313056',
    projectId: 'harsh-potfolio',
    storageBucket: 'harsh-potfolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_QBFQrQgrr0ZcP9fEp5QDtXJ_zksBr4E',
    appId: '1:56301313056:ios:0c8b67fe858a778c5e7045',
    messagingSenderId: '56301313056',
    projectId: 'harsh-potfolio',
    storageBucket: 'harsh-potfolio.appspot.com',
    iosBundleId: 'com.harsh.workspace.harshPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_QBFQrQgrr0ZcP9fEp5QDtXJ_zksBr4E',
    appId: '1:56301313056:ios:0c8b67fe858a778c5e7045',
    messagingSenderId: '56301313056',
    projectId: 'harsh-potfolio',
    storageBucket: 'harsh-potfolio.appspot.com',
    iosBundleId: 'com.harsh.workspace.harshPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgEn3CmxmRmbIa2uEPL2l732hrWiPb_1c',
    appId: '1:56301313056:web:d51a71a3b61d4bc15e7045',
    messagingSenderId: '56301313056',
    projectId: 'harsh-potfolio',
    authDomain: 'harsh-potfolio.firebaseapp.com',
    storageBucket: 'harsh-potfolio.appspot.com',
    measurementId: 'G-WLZ8LV9WHH',
  );

}